use crate::filter::FilteredEntry;

//Generate a shell script string from a list of filtered entries.
// Handles directory changes inline so the script replays correctly.

pub fn generate(entries: Vec<FilteredEntry>) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut current_dir: Option<String> = None;

    lines.push("#!/usr/bin/env bash".to_string());
    lines.push("set -e #exit on first error".to_string());
    lines.push(String::new());
    lines.push("# Generated by trapsh".to_string());
    lines.push(String::new());

    for entry in entries {
        let dir_changes = current_dir.as_deref() != Some(&entry.dir);
        if dir_changes {
            lines.push(format!("cd \"{}\"", entry.dir));
            current_dir = Some(entry.dir.clone());
        }
        lines.push(entry.cmd.clone());
    }

    lines.join("\n") + "\n"
}
